// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewxbhwlgabglkndrwqgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3eGJod2xnYWJnbGtuZHJ3cWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTg4MjYsImV4cCI6MjA2NjE5NDgyNn0.2HB4ERgdNzr5YoJYXNv-zSbaW-e-zCVRjwOZNLUm1VM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);